toc:
    - name: Turtles, Patches, and Links
    - Turtle
    - Turtles
    - Link
    - Links
    - Patch
    - Patches
    - AgentSet
    - AgentArray
    - name: The Model
    - Model2D
    - Model3D
    - Model
    - World
    - name: The View
    - TwoDraw
    - ThreeDraw
    - Color
    - name: Interaction
    - Mouse
    - name: Data
    - DataSet
    - name: Utilities
      description: |
          An assortment of helper functions. To use: `import * as util from src/utils.js`.
    # - utils

    # - randomInt
    # - randomInt2
    # - randomFloat
    # - randomFloat2
    # - name: Other
    # - DataSet
